# Generated by Django 3.1.4 on 2021-01-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_nascimento', models.DateTimeField(auto_now_add=True)),
                ('data_de_atualização', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=300)),
                ('info', models.TextField()),
                ('status', models.BooleanField(choices=[(True, 'Feita'), (False, 'Pendente')])),
            ],
        ),
    ]
