# Generated by Django 3.1.4 on 2021-01-13 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefas',
            old_name='data_de_atualização',
            new_name='data_de_edit',
        ),
    ]
